language: python

# No python2!
python:
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.10 DJANGO_SETTINGS_MODULE=shop.test_settings

install:
  - pip install -q Django==$DJANGO
  - pip install -q .
  - pip install -qr requirements.txt

script: python manage.py test